### PR TITLE
Raise an exception if trailer Root is not a dict

### LINKED ISSUE #218: Malformed PDF raises `no implicit conversion of Symbol into Integer (TypeError)`
pdf-reader crashes with the attached malformed PDF file.

[20170708114003906949634_test_0151.pdf](https://github.com/yob/pdf-reader/files/1133073/20170708114003906949634_test_0151.pdf)

### Crash

```
[*] Processing 'crashes/20170708114003906949634_test_0151.pdf'
[+] Processing complete
[*] Parsing 'crashes/20170708114003906949634_test_0151.pdf'
[*] Version: 1.4
[*] Info: {:Creator=>"Writer", :Producer=>"OpenOffice.org 2.0", :CreationDate=>"D:20080409174640-04'00'"}
/usr/local/rvm/gems/ruby-2.3.0/gems/pdf-reader-2.0.0/lib/pdf/reader.rb:125:in `[]': no implicit conversion of Symbol into Integer (TypeError)
	from /usr/local/rvm/gems/ruby-2.3.0/gems/pdf-reader-2.0.0/lib/pdf/reader.rb:125:in `metadata'
	from ./read-pdf.rb:72:in `parse'
	from ./read-pdf.rb:55:in `read'
	from ./read-pdf.rb:96:in `<main>'
```

### Reproduce

```
#!/usr/bin/env ruby
require 'pdf-reader'
require 'colorize'

$QUIET = false

#
# Print status message
#
# @param [String] msg message to print
#
def print_status(msg = '')
  puts '[*] '.blue + msg unless $QUIET
end

#
# Print progress messages
#
# @param [String] msg message to print
#
def print_good(msg = '')
  puts '[+] '.green + msg unless $QUIET
end

#
# Print error message
#
# @param [String] msg message to print
#
def print_error(msg = '')
  puts '[-] '.red + msg unless $QUIET
end

#
# Read a PDF file
#
# @param [File] file PDF file
#
def read doc
  print_status "Processing '#{doc}'"
  begin
    @fname = doc
    reader = PDF::Reader.new(@fname)
  rescue PDF::Reader::MalformedPDFError
    print_error "Could not parse PDF '#{doc}': PDF is malformed"
    exit 1
  rescue PDF::Reader::UnsupportedFeatureError 
    print_error "Could not parse PDF '#{doc}': PDF::Reader::UnsupportedFeatureError"
    exit 1
  end
  print_good 'Processing complete'

  print_status "Parsing '#{@fname}'"
  begin
    parse reader
  rescue PDF::Reader::UnsupportedFeatureError
    print_error "Could not parse PDF '#{doc}': PDF::Reader::UnsupportedFeatureError"
    exit 1
  rescue PDF::Reader::MalformedPDFError => e
    print_error "Could not parse PDF '#{doc}': PDF is malformed"
    exit 1
  end
  print_good 'Parsing complete'
end

#
# parse pdf
#
def parse(reader)
  print_status "Version: #{reader.pdf_version}"
  print_status "Info: #{reader.info}"
  print_status "Metadata: #{reader.metadata}"
  print_status "Objects: #{reader.objects}"
  print_status "Pages: #{reader.page_count}"

  print_status 'Dumping PDF contents...'
  contents = ''
  reader.pages.each do |page|
    contents << page.text.to_s
    contents << page.fonts.to_s
    contents << page.text.to_s
    contents << page.raw_content.to_s
  end
  #puts contents unless $QUIET
end

def usage
  print_status "./read-pdf.rb <FILE>"
  exit 1
end

doc = ARGV[0]
usage if doc.nil?

if File.exist? doc
  read doc
  exit 0
else
  print_error "Could not find #{doc}"
  exit 1
end
```

### LINKED ISSUE #219: Malformed PDF raises `undefined method `[]' for nil:NilClass (NoMethodError)`
pdf-reader crashes with the attached malformed PDF file.

[20170708112725541239869_test_0033.pdf](https://github.com/yob/pdf-reader/files/1133080/20170708112725541239869_test_0033.pdf)

### Crash

```
[*] Processing 'crashes/20170708112725541239869_test_0033.pdf'
[+] Processing complete
[*] Parsing 'crashes/20170708112725541239869_test_0033.pdf'
[*] Version: 1.4
[*] Info: 
/usr/local/rvm/gems/ruby-2.3.0/gems/pdf-reader-2.0.0/lib/pdf/reader.rb:125:in `metadata': undefined method `[]' for nil:NilClass (NoMethodError)
	from ./read-pdf.rb:72:in `parse'
	from ./read-pdf.rb:55:in `read'
	from ./read-pdf.rb:96:in `<main>'
```

### Reproduce

```
#!/usr/bin/env ruby
require 'pdf-reader'
require 'colorize'

$QUIET = false

#
# Print status message
#
# @param [String] msg message to print
#
def print_status(msg = '')
  puts '[*] '.blue + msg unless $QUIET
end

#
# Print progress messages
#
# @param [String] msg message to print
#
def print_good(msg = '')
  puts '[+] '.green + msg unless $QUIET
end

#
# Print error message
#
# @param [String] msg message to print
#
def print_error(msg = '')
  puts '[-] '.red + msg unless $QUIET
end

#
# Read a PDF file
#
# @param [File] file PDF file
#
def read doc
  print_status "Processing '#{doc}'"
  begin
    @fname = doc
    reader = PDF::Reader.new(@fname)
  rescue PDF::Reader::MalformedPDFError
    print_error "Could not parse PDF '#{doc}': PDF is malformed"
    exit 1
  rescue PDF::Reader::UnsupportedFeatureError 
    print_error "Could not parse PDF '#{doc}': PDF::Reader::UnsupportedFeatureError"
    exit 1
  end
  print_good 'Processing complete'

  print_status "Parsing '#{@fname}'"
  begin
    parse reader
  rescue PDF::Reader::UnsupportedFeatureError
    print_error "Could not parse PDF '#{doc}': PDF::Reader::UnsupportedFeatureError"
    exit 1
  rescue PDF::Reader::MalformedPDFError => e
    print_error "Could not parse PDF '#{doc}': PDF is malformed"
    exit 1
  end
  print_good 'Parsing complete'
end

#
# parse pdf
#
def parse(reader)
  print_status "Version: #{reader.pdf_version}"
  print_status "Info: #{reader.info}"
  print_status "Metadata: #{reader.metadata}"
  print_status "Objects: #{reader.objects}"
  print_status "Pages: #{reader.page_count}"

  print_status 'Dumping PDF contents...'
  contents = ''
  reader.pages.each do |page|
    contents << page.text.to_s
    contents << page.fonts.to_s
    contents << page.text.to_s
    contents << page.raw_content.to_s
  end
  #puts contents unless $QUIET
end

def usage
  print_status "./read-pdf.rb <FILE>"
  exit 1
end

doc = ARGV[0]
usage if doc.nil?

if File.exist? doc
  read doc
  exit 0
else
  print_error "Could not find #{doc}"
  exit 1
end
```

### PR DESCRIPTION
**Pull request by ndbroadbent**
* Fixes #218 
* Fixes #219

### CODE REVIEW

File: lib/pdf/reader.rb [hunk 1]
```diff
@@ -241,7 +241,12 @@ def utf16_to_utf8(obj)
     end
 
     def root
-      @root ||= @objects.deref(@objects.trailer[:Root])
+      return @root if @root
+      @root = @objects.deref(@objects.trailer[:Root])
+      unless @root.kind_of?(::Hash)
+        raise MalformedPDFError, "PDF malformed, trailer Root should be a dictionary"
+      end
+      @root
```
Comment (yob) [inline lib/pdf/reader.rb]: To avoid the early return and instance variable dance, are you open to something like this?

```diff
diff --git a/lib/pdf/reader.rb b/lib/pdf/reader.rb
index 9a87ca8..6ce7986 100644
--- a/lib/pdf/reader.rb
+++ b/lib/pdf/reader.rb
@@ -241,12 +241,13 @@ module PDF
     end

     def root
-      return @root if @root
-      @root = @objects.deref(@objects.trailer[:Root])
-      unless @root.kind_of?(::Hash)
-        raise MalformedPDFError, "PDF malformed, trailer Root should be a dictionary"
+      @root ||= begin
+        obj = @objects.deref(@objects.trailer[:Root])
+        unless obj.kind_of?(::Hash)
+          raise MalformedPDFError, "PDF malformed, trailer Root should be a dictionary"
+        end
+        obj
       end
-      @root
```

Using `Object#tap` might clean it up even more, but it's not available all the way back to 1.9.

File: spec/integrity.yml [hunk 2]
```diff
@@ -292,7 +295,7 @@ data/type3_font.pdf:
   :md5: ef2a3eb57d5996c4a33681e1aec98f2c
 data/type3_font_with_rare_font_matrix.pdf:
   :bytes: 11541
-  :md5: 08f69084d72dabc5dfdcf5c1ff2a719f
+  :md5: '08f69084d72dabc5dfdcf5c1ff2a719f'
```
Comment (yob) [inline spec/integrity.yml]: Out of interest, what version of ruby (and what YAML lib) are you using? It'd be helpful if PR diffs didn't include unrelated changes like these.

File: spec/reader_spec.rb [hunk 3]
```diff
@@ -128,4 +128,11 @@
     end
   end
 
+  describe "#root" do
+    it "raises an exception if trailer Root is not a dict" do
+      filename = pdf_spec_file("trailer_root_is_not_a_dict")
+      pdf = PDF::Reader.new(filename)
+      expect { pdf.send :root }.to raise_error(PDF::Reader::MalformedPDFError)
+    end
+  end
```
Comment (yob) [inline spec/reader_spec.rb]: My strong preference is to not test private methods using `Object#send`.

A spec that tests `root` indirectly via the `metadata` or  `page_count` methods would be ace. An additional spec at the bottom of `spec/integration_spec.rb` would also be good - I rely on those to prevent regressions in the public API when internal refactoring happens.

File: lib/pdf/reader.rb (hunk 1 above)
Comment (ndbroadbent) [reply lib/pdf/reader.rb]: 👍

File: spec/integrity.yml (hunk 2 above)
Comment (ndbroadbent) [reply spec/integrity.yml]: Sorry I'm on Ruby 2.3.3p222. And I think YAML is included in Ruby, I can't see it as a gem.

But yes will revert those unrelated changes

Comment (ndbroadbent) [reply spec/integrity.yml]: I think YAML is just adding quotes around strings that start with "0", in case they are parsed as octals.

File: spec/reader_spec.rb (hunk 3 above)
Comment (ndbroadbent) [reply spec/reader_spec.rb]: 👍 Have changed the test to call `pdf.metadata`, and added another spec to `spec/integration_spec.rb.

**Comment by ndbroadbent** [comment]
Have pushed all those changes

**Comment by yob** [comment]
Thanks!
