### PR TITLE
Fix extraction of text from built-in fonts with difference tables

### LINKED ISSUE #211: Incorrect encoding of open and close double quotes and of ligatures
The attached PDF contains a single line of text:

_This PDF contains ligatures, for example in “file” and “floor”._

(And of course the PDF really does have curly double quotes and fi and fl ligatures.)

However, this code:
```ruby
require 'pdf/reader'
filename = ARGV.pop
reader = PDF::Reader.new(filename)
reader.pages.each do |page|
  puts page.text
end
```
Produces this **incorrect** output:
_This PDF contains ligatures,for example in …‡le†and …ˆoor†._

[test.pdf](https://github.com/yob/pdf-reader/files/860872/test.pdf)

### PR DESCRIPTION
**Pull request by yob**
We were ignoring the difference table for built in fonts that:

1. use an old style encoding (like WinAnsi)
2. have a difference table that modifies bytes that are explicitly specified in the encoding

The problem: we were loading the difference table into our encoding map, but then replacing it with the default mapping for the encoding.

The fix: load the default mapping for the encoding first, then load the difference table.

Closes #211

### CODE REVIEW

File: spec/integration_spec.rb [hunk 1]
```diff
@@ -70,6 +70,17 @@
     end
   end
 
+  context "PDF with a difference table (v2)" do
+    let(:filename) { pdf_spec_file("difference_table2") }
+
+    it "extracts text correctly" do
+      PDF::Reader.open(filename) do |reader|
+        page = reader.page(1)
+        expect(page.text).to eql("This PDF contains ligatures,for example in “ﬁle”and “ﬂoor”.")
```
Comment (yob) [inline spec/integration_spec.rb]: This isn't perfect - it'd be nice to convert the `ﬁ` and `ﬂ` ligatures to `fi` and `fl`. Still this is better than what we had.
